"""initial tables users trackings price_history

Revision ID: 0b02ae8f12cd
Revises: 
Create Date: 2026-08-18 18:04:17.140772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b02ae8f12cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('preferred_notification', sa.String(length=50), server_default='telegram', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('trackings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin_code', sa.String(length=50), nullable=False),
    sa.Column('destination_code', sa.String(length=50), nullable=False),
    sa.Column('origin_name', sa.String(length=255), nullable=False),
    sa.Column('destination_name', sa.String(length=255), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('car_type', sa.String(length=50), nullable=True),
    sa.Column('transport_type', sa.String(length=50), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_tracking', 'trackings', ['user_id', 'origin_code', 'destination_code', 'departure_date', 'transport_type'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('price_history',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carrier', sa.String(length=255), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tracking_id'], ['trackings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'tracking_id')
    )
    op.create_index('idx_price_history_tracking_id', 'price_history', ['tracking_id', sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_history_tracking_id', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('idx_unique_tracking', table_name='trackings', postgresql_where=sa.text('is_active = true'))
    op.drop_table('trackings')
    op.drop_table('users')
    # ### end Alembic commands ###
