"""update_price_history_schema

Revision ID: 1bfe4536d1b9
Revises: 0b02ae8f12cd
Create Date: 2026-08-20 17:18:19.893126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfe4536d1b9'
down_revision: Union[str, Sequence[str], None] = '0b02ae8f12cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_price_history_tracking_id'), table_name='price_history')
    op.create_index('idx_price_history_tracking_time', 'price_history', ['tracking_id', sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_history_tracking_time', table_name='price_history')
    op.create_index(op.f('idx_price_history_tracking_id'), 'price_history', ['tracking_id', sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###
