"""add_stations_table

Revision ID: 356c321e2170
Revises: 4cc7c9c128f1
Create Date: 2026-09-23 15:29:19.498331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356c321e2170'
down_revision: Union[str, Sequence[str], None] = '4cc7c9c128f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_popular', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_stations_is_popular', 'stations', ['is_popular'], unique=False)
    op.create_index('idx_stations_name_trgm', 'stations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stations_name_trgm', table_name='stations')
    op.drop_index('idx_stations_is_popular', table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
