"""add last_notified_price to trackings

Revision ID: 4cc7c9c128f1
Revises: 5b79e389bd1c
Create Date: 2026-09-08 12:28:13.634588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc7c9c128f1'
down_revision: Union[str, Sequence[str], None] = '5b79e389bd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackings', sa.Column('last_notified_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackings', 'last_notified_price')
    # ### end Alembic commands ###
