"""drop route column and refresh price column

Revision ID: 5b79e389bd1c
Revises: 1bfe4536d1b9
Create Date: 2026-08-27 17:21:55.900715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b79e389bd1c'
down_revision: Union[str, Sequence[str], None] = '1bfe4536d1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trackings', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('trackings', 'route')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackings', sa.Column('route', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('trackings', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
