"""remove_unique_constraint_from_station_name

Revision ID: e694e0d902cd
Revises: 356c321e2170
Create Date: 2026-09-29 12:15:19.526535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e694e0d902cd'
down_revision: Union[str, Sequence[str], None] = '356c321e2170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stations_name_key'), 'stations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('stations_name_key'), 'stations', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
